language: ruby

before_install:
  - rvm @global do gem uninstall bundler --all --executables
  - gem uninstall bundler --all --executables
  - gem install bundler --version '~> 1.5.2'
  - bundle --version
bundler_args: --without=development

rvm: 2.0.0
env:
  - VAGRANT_VERSION=v1.6.5 BERKSHELF_VERSION=v3.0.1
  - VAGRANT_VERSION=v1.6.5 BERKSHELF_VERSION=v3.0.0

matrix:
  include:
    - env:
        - VAGRANT_VERSION=v1.5.4 BERKSHELF_VERSION=v3.0.1
        - VAGRANT_VERSION=v1.5.4 BERKSHELF_VERSION=v3.0.0
    - env:
        - VAGRANT_VERSION=v1.4.3 BERKSHELF_VERSION=v3.0.1
        - VAGRANT_VERSION=v1.4.3 BERKSHELF_VERSION=v3.0.0
    - env:
        - VAGRANT_VERSION=v1.3.5 BERKSHELF_VERSION=v3.0.1
        - VAGRANT_VERSION=v1.3.5 BERKSHELF_VERSION=v3.0.0
      rvm: 1.9.3
    - env:
        - VAGRANT_VERSION=v1.2.7 BERKSHELF_VERSION=v3.0.1
        - VAGRANT_VERSION=v1.2.7 BERKSHELF_VERSION=v3.0.0
      rvm: 1.9.3
    - env:
        - VAGRANT_VERSION=master BERKSHELF_VERSION=v3.0.1
        - VAGRANT_VERSION=master BERKSHELF_VERSION=v3.0.0
  allow_failures:
    - env:
        - VAGRANT_VERSION=master BERKSHELF_VERSION=v3.0.1
        - VAGRANT_VERSION=master BERKSHELF_VERSION=v3.0.0

notifications:
  hipchat:
    rooms:
      secure: C+gu4OY+FNhJPrm7HbNvn82C7VEU3G+BRSFeSRpZc6hfKkDOKghTLFlc1NjLKyPdFk6t4qSa4pptUwH9TP+ytImBqqM6BPD8eviO493j1bclXNnNxW+RytCpAwvQTcOVDalzBFvx/jA0uGpAuitBubgpmAhPHc9ddtOnKbEuxEM=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
      - '%Build details: %{build_url}'
