# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  #config.opsworks.stack_id = 'd5936be4-a3cd-4629-9311-f75103e7c5c7'
  config.opsworks.ignore_instances = ['aws-web02', 'aws-web03', 'aws-web04']
  config.opsworks.ignore_recipes = ['route53::setup','deploy::composer']
end
